<?php

use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\Core\Controller\ControllerBase;
use Google\Cloud\Dialogflow\V2\SessionsClient;
use Google\Cloud\Dialogflow\V2\TextInput;
use Google\Cloud\Dialogflow\V2\QueryInput;
use Google\Cloud\Dialogflow\V2\IntentsClient;
use Google\Cloud\Dialogflow\V2\Intent;
use Google\Cloud\Dialogflow\V2\Intent\TrainingPhrase\Part;
use Google\Cloud\Dialogflow\V2\Intent\TrainingPhrase;
use Google\Cloud\Dialogflow\V2\Intent\Message;
use Google\Cloud\Dialogflow\V2\Intent\Message\Text;

/**
 * Implements hook_menu().
 */
function vmlyr_itau_bot_menu() {
  $items['chat'] = array(
    'title' => 'Chat',
    'page callback' => '_vmlyr_itau_bot_callback',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['chat-ajax'] = array(
    'title' => 'Chat',
    'page callback' => '_vmlyr_itau_bot_callback_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function vmlyr_itau_bot_libraries_info() {
  $libraries['google-cloud-php-dialogflow'] = array(
    'name' => 'Dialog Flow',
    'vendor url' => 'https://dialogflow.com/',
    'download url' => 'https://github.com/dialogflow/dialogflow-php',
    'version' => '2',
    'dependencies' => array(),
    'files' => array(
      'php' => array(
        'vendor/autoload.php'
      ),
    ),
  );
  return $libraries;
}

/**
 * Callback Chat
 */
function _vmlyr_itau_bot_callback(){
  $build['#attached']['js'][] = drupal_get_path('module', 'vmlyr_itau_bot') . '/js/vmlyr_itau_bot.js';

  $build['list_chat'] = [
    '#markup' => '<ul id="list-chat"><li>¡Hola!</li></ul>',
  ];

  $build['text_message'] = [
    '#type' => 'textfield',
    '#id' => 'text-message'
  ];

  $build['send_message'] = [
    '#type' => 'submit',
    '#id' => 'send-message',
    '#value' => t('Send')
  ];
  return $build;
}

/**
 * Callback Chat
 */
function _vmlyr_itau_bot_callback_ajax(){
  $library = libraries_load('google-cloud-php-dialogflow');
  if (($library = libraries_load('google-cloud-php-dialogflow')) && !empty($library['loaded'])) {
    $text = $_POST['text'];
    $credentials = array('credentials' =>  drupal_get_path('module', 'vmlyr_itau_bot') . '/certs.json');
    $projectName = "test-api-221719";
    $sessionsClient = new SessionsClient($credentials);
    $session = $sessionsClient->sessionName($projectName, uniqid());
    $languageCode = 'es';

    // create text input
    $textInput = new TextInput();
    $textInput->setText($text);
    $textInput->setLanguageCode($languageCode);

    // create query input
    $queryInput = new QueryInput();
    $queryInput->setText($textInput);

    // get response and relevant info
    $response = $sessionsClient->detectIntent($session, $queryInput);
    $queryResult = $response->getQueryResult();
    $queryText = $queryResult->getQueryText();
    $intent = $queryResult->getIntent();
    $displayName = $intent->getDisplayName();
    $confidence = $queryResult->getIntentDetectionConfidence();
    $fulfilmentText = $queryResult->getFulfillmentText();

    $build = [
      '#markup' => $fulfilmentText,
    ];

    $response = array("success"=>true,"response"=>$fulfilmentText);
  }else{
    $response = array("success"=>error,"response"=>"not_library");
  } 
  drupal_json_output($response);
}